# Generated by Django 3.2 on 2021-04-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('beach_name', models.CharField(max_length=60)),
                ('ocean', models.CharField(max_length=60)),
                ('nearest_airport', models.CharField(max_length=60)),
                ('shark_activity', models.CharField(max_length=60)),
                ('anual_shark_attacks', models.IntegerField(default=0)),
                ('required_experience', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('surf_experiece', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=60)),
                ('used', models.CharField(max_length=60)),
                ('warranty', models.CharField(max_length=60)),
                ('images', models.FileField(upload_to='report/static/images')),
                ('date_posted', models.DateTimeField()),
            ],
        ),
    ]
